apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend-deployment
spec:
  replicas: {{ .Values.replicaCount}}
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: elenagolikova/dos_back_app:{{ .Values.tag.id}}
        env:
          - name: DATASOURCE_USERNAME
            valueFrom:
              secretKeyRef:
                name: secret-db
                key: username
          - name: DATASOURCE_PASSWORD
            valueFrom:
              secretKeyRef:
                 name: secret-db
                 key: password
